_target_: dataloader
opt:
  data_path: 'data/mRI/all_data_list.npy'
  raw_data_path: 'data/mRI/'
  pc_num: 512
  isTrain: True
  use_generated_data_file: True
  noise_mean: 0.005
  noise_var: 0.005
  number_points_sample: 1024
  hasmesh: True
  joint_train_epoch: 50
  z_kl: 1e-5
  z_flow: 0.1
  pc_re: 50
  mm_re: 50
  em: 5
  mmem: 5
  mcl: 0.1
  reg: 0
  one_stage_lr: 1e-3
  two_stage_lr: 1e-4 
  cl_temperature: 1
  enhance_cl: False
  encoder_feed_drop: 0
  drop_rate: 0

dataname: mri